- id: add-ticket-to-commit
  name: Add ticket ID to commit message
  description: prepare-commit-msg hook for adding ticket code with pre-commit.
  entry: ./scripts/add-ticket-to-commit.sh
  stages:
    - prepare-commit-msg
  language: script
  always_run: true

- id: shellcheck
  name: Shellcheck bash scripts
  description: Check Bash scripts using shellcheck
  entry: ./scripts/validate-bash.sh
  language: script
  types:
    - executable
  stages:
    - commit
