minimum_pre_commit_version: "1.15"
default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/motivozwolle/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
    - id: lint-php
      name: Lint PHP
      description: Lint PHP code
      entry: php -l
      language: system
      files: '.php$'
